name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ Note
        Before you submit an issue, please perform the following first:

        1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
        2. Re-initialize the project root to pull down modules: `terraform init`
        3. Re-attempt your terraform plan or apply and check if the issue still persists
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please provide a clear and concise description of the issue you are encountering, your current setup, and what steps led up to the issue. If you can provide a reproduction, that will help tremendously.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Terraform Version
      description: Paste `terraform version` output
      render: shell
    validations:
      required: true
  - type: textarea
    id: plan
    attributes:
      label: terraform plan
      description: Please copy and paste any relevant `terraform plan`
      render: shell
  - type: textarea
    id: apply
    attributes:
      label: terraform apply
      description: Please copy and paste any relevant `terraform apply`
      render: shell
